//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Estudiantes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GESTION_ESTUDIANTESEntities : DbContext
    {
        public GESTION_ESTUDIANTESEntities()
            : base("name=GESTION_ESTUDIANTESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Asignatura> tbl_Asignatura { get; set; }
        public virtual DbSet<tbl_Control_asistencia> tbl_Control_asistencia { get; set; }
        public virtual DbSet<tbl_Docente> tbl_Docente { get; set; }
        public virtual DbSet<tbl_Estudiante> tbl_Estudiante { get; set; }
    }
}
