//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Estudiantes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Control_asistencia
    {
        public int Id_Control_asistencia { get; set; }
        public string Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<int> matr_estudiante { get; set; }
    
        public virtual tbl_Estudiante tbl_Estudiante { get; set; }
    }
}
